export const ADMIN_PRODUCT_TYPE_CATEGORY_FIELDS = /* GraphQL */ `
  id
  slug
  shopSlug
  name
  nameEs
  nameEn
  description
  sortOrder
  isActive
  showInNav
  cardImageUrl
  cardImagePublicId
  cardImageAlt
  cardImageThumbUrl
  productCount
  activeProductCount
  createdAt
  updatedAt
`
